### ISSUE TITLE
Cloudflare scraping failed

### ISSUE THREAD

**Issue by 89yoyos** [Anorov/cloudflare-scrape#146]
Opened SickRage today, and my log was filled with about a dozen messages like this:

Please read https://github.com/Anorov/cloudflare-scrape#updates, then file a bug report at https://github.com/Anorov/cloudflare-scrape/issues." 2018-04-05 02:57:55 FINDPROPERS :: [Torrent9] :: [1d34bcb] Request failed: Error parsing Cloudflare IUAM Javascript challenge. Cloudflare may have changed their technique, or there may be a bug in the script.

I’m using the latest version of SickRage, running on Ubuntu.

**Comment by phinxy** [comment]
I got the same errors today on Debian stretch.

**Comment by pl77** [comment]
Please check closed issue 145 and update to the latest 1.9.5.

**Comment by Anorov** [comment]
This should be fixed. Please make sure you're using the latest version (1.9.5).

**Comment by Dohnerd** [comment]
Still getting the error after cfscrape update

2018-04-06 11:37:23 SEARCHQUEUE-DAILY-SEARCH :: [Torrentz] :: [1d34bcb] Request failed: Error parsing Cloudflare IUAM Javascript challenge. Cloudflare may have changed their technique, or there may be a bug in the script.

[/] # pip show cfscrape
Name: cfscrape
Version: 1.9.5

**Comment by pl77** [comment]
@Dohnerd I usually put the line `print("CFSCRAPE VERSION:", cfscrape.__version__)` at the start of any script where I run cfscrape just to make sure that it's working in whichever python environment it's running in.  Does it output 1.9.5 if you put that line in your code?

**Comment by Dohnerd** [comment]
code ?
