### ISSUE TITLE
2.0.1 and 2.0.2 crashes opening user_agents.json

### ISSUE THREAD

**Issue by lukastribus** [Anorov/cloudflare-scrape#237]
The pip installation does not ship `user_agents.json` therefor, cfscrape (`2.0.1` and `2.0.2`) crashes:

```
mkdir cfscrapetest
cd cfscrapetest/
pipenv --three
pipenv install cfscrape
pipenv run python
Python 3.5.2 (default, Nov 23 2017, 16:37:01)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cfscrape
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.local/share/virtualenvs/cfscrapetest-uMJOQPOp/lib/python3.5/site-packages/cfscrape/__init__.py", line 22, in <module>
    with open(USER_AGENTS_PATH) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/.local/share/virtualenvs/cfscrapetest-uMJOQPOp/lib/python3.5/site-packages/cfscrape/user_agents.json'
>>>

```

@Anorov @pro-src

**Comment by Anorov** [comment]
This is fixed in the latest version. Please upgrade with `pip install -U cfscrape`.

**Comment by Xonshiz** [comment]
Unfortunately, I'm still having this issue. I've got cfscrape 2.0.4, which I pulled from pip. Any clue why this might be happening?

**Comment by pro-src** [comment]
Hi @Xonshiz,

If I had to guess, you're still using an older version of the package.

Verify the version:
`python -c 'import cfscrape; print(cfscrape.__version__)'`

Check to see if the file exists and print it's contents:
`python -c 'import cfscrape; import os; print(open(os.path.join(cfscrape.__path__[0], "user_agents.json"), "r").read())'`

Those two commands should really pinpoint the issue. If you get an error stacktrace and you're using the latest version, please share the stacktrace with the `python --version`.

**Comment by Xonshiz** [comment]
I ran both commands, the version I have is "2.0.4" and the second commands prints the content of that JSON file, all the user agents..

So, I have the latest version and the file as well. Python version is working, but pyinstaller isn't making exe out of it properly.

**Comment by pro-src** [comment]
So this definitely isn't a problem with cfscrape.

https://pyinstaller.readthedocs.io/en/v3.3.1/spec-files.html#adding-files-to-the-bundle
https://pyinstaller.readthedocs.io/en/v3.3.1/spec-files.html#adding-data-files

https://en.wikipedia.org/wiki/Stack_Overflow

**Comment by Xonshiz** [comment]
Yeah, seems like it. I've been working with PyInstaller with the same setup just fine. Just started causing issue and that too related with cfscrape. The thing is that it came after I updated cfscrape to the latest version 2.0.4. Earlier it worked just fine. Maybe it's that user_agent.json not being added, might have to add it in spec.

**Comment by pro-src** [comment]
Might?

**Comment by pro-src** [comment]
https://github.com/pyinstaller/pyinstaller/issues/3292#issuecomment-364980024

**Comment by Xonshiz** [comment]
If somebody stumbles upon this and is in the same jeopardy, make your `.spec` file and in the `datas=[]` section, add this.

    datas=[('{YourPythonDirectory}\\Lib\\site-packages\\cfscrape\\user_agents.json', 'cfscrape')]

This should work.

**Comment by Anorov** [comment]
@Xonshiz That shouldn't be necessary in the latest version. Do you still experience any issues after updating?

**Comment by pro-src** [comment]
@Anorov it's completely necessary because he is creating an executable using pyinstaller which doesn't process `MANIFEST.in` files. It's a pyinstaller issue that is essentially labeled as `wontfix`.

**Comment by Xonshiz** [comment]
Yes @Anorov . But, this issue isn't related to cfscrape. I was having the same issue, but if anyone's using pyinstaller to make the executables, they need to do this. Let this issue be closed, because it has been fixed and is working just fine.

**Comment by pro-src** [comment]
We don't really gain anything by the UAs being in a `.json` file since it just gets translated to a python list at runtime. The JSON file is small and could be embedded in a python file. Although, it's hard to justify the change when the only known use case is pyinstaller. There is also the case where new header related information would ideally be added to it and separate from the python code.

That said, even if we wanted to work around this for now, there's a good chance that we'd want to revert back to using `.json` file in the future. i.e. If it were to grow to become something like: https://github.com/pro-src/user-agent-info/blob/master/browsers.json
This is a python library that is depending on non-python data files so I think there is some room for discussion here.

**Comment by Anorov** [comment]
@pro-src Ah, that makes sense. Didn't look at the issue link and just figured PyInstaller would've included it.

I'm starting to regret my decision to move the user-agent strings into a JSON file. I'm just going to make it a Python file instead, and import it.

**Comment by Anorov** [comment]
2.0.7 now uses a Python file to store the user-agent strings: https://github.com/Anorov/cloudflare-scrape/releases/tag/2.0.7

**Comment by Xonshiz** [comment]
You did not need to go through such lengths. Thanks a ton man!

**Comment by Xonshiz** [comment]
But, for reference, in future if anyone stumbles upon this area, please do refer to my comments above and the links and mentions by @pro-src
