### ISSUE TITLE
Setting cookies doesn't work

### ISSUE THREAD

**Issue by Limero** [Anorov/cloudflare-scrape#30]
If you manually set your own cookies, the cookies will not be set if it's used on a page with Cloudflare anti-bot. It seems like they get overwritten with cf_clearance and cfduid, instead of it being merged.

The following **does** work if used on page without Cloudflare, but not on a page with it:
scraper.get("http://somesite.com", cookies=cookies)

**Comment by Anorov** [comment]
I've just released an update, and I was not able to reproduce this issue in it. Can you tell me if the updated version has resolved this issue?

**Comment by Limero** [comment]
The issue is still there. Here is example code that you can use:
`
import cfscrape

cookies = {
    'test': 'abc'
}

r = cfscrape.create_scraper().get('https://en.nostalrius.org/', cookies=cookies)
print(r.cookies)
`

Result with current cloudflare-scrape:
<RequestsCookieJar[]>

Result with my branch:
<RequestsCookieJar[<Cookie test=abc for />, <Cookie __cfduid=d3800b853b48d4ca4edeb5c8a9100a5c61460916141 for .nostalrius.org/>]>

As far as I can see, with the current version, you get no cookies at all. When I did my changes, the only cookies that you got were the ones set by the site (not test=abc cookie).

**Comment by Anorov** [comment]
By default, requests doesn't include cookies in the `cookies` attribute of the response, so `r.cookies` will always be blank there. Also, keep in mind that when you send cookies to a site, that has no relation to what cookies the server will set.

If you want to constantly include cookies with every request, you will need to modify the session object's cookie store. Example:

    scraper = cfscrape.create_scraper()
    # Manipulate scraper.cookies

Please consult the requests documentation for information on how to add cookies to the session.

If this doesn't resolve your issue, please reply to this thread again.
